#!/usr/bin/env bash

# Get directory of this script
# Source: https://stackoverflow.com/a/246128
SOURCE="${BASH_SOURCE[0]}"
while [ -h "$SOURCE" ]; do # resolve $SOURCE until the file is no longer a symlink
  DIR="$( cd -P "$( dirname "$SOURCE" )" >/dev/null 2>&1 && pwd )"
  SOURCE="$(readlink "$SOURCE")"
  [[ $SOURCE != /* ]] && SOURCE="$DIR/$SOURCE" # if $SOURCE was a relative symlink, we need to resolve it relative to the path where the symlink file was located
done
DIR="$( cd -P "$( dirname "$SOURCE" )" >/dev/null 2>&1 && pwd )"

# Get Python 3 executable
PYTHON3=$(which python3)

# Add dynalist_utils to lib path
export PYTHONPATH=${DIR}/../../lib:${PYTHONPATH}

${PYTHON3} ${DIR}/dlget.py $*
